# Generated by Django 5.1.15 on 2026-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_area',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('helios', 'Helios')], default='', help_text='Správce vidí pouze tikety dané oblasti. Ponechte prázdné pro přístup ke všem oblastem.', max_length=20, verbose_name='oblast správce'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_companies',
            field=models.ManyToManyField(blank=True, help_text='Správce vidí pouze tikety těchto firem. Ponechte prázdné pro přístup ke všem firmám.', related_name='managing_managers', to='accounts.company', verbose_name='spravované firmy'),
        ),
    ]
