# Generated by Django 5.1.15 on 2026-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_resolver_areas'),
        ('tickets', '0009_workcategory_ticket_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requester_areas',
            field=models.ManyToManyField(blank=True, help_text='Zobrazí se pouze tikety firmy z těchto oblastí. Vlastní tikety jsou viditelné vždy.', related_name='requester_users', to='tickets.area', verbose_name='oblasti žadatele'),
        ),
        migrations.AddField(
            model_name='user',
            name='requester_scope',
            field=models.CharField(choices=[('own', 'Pouze vlastní tikety'), ('company', 'Všechny tikety firmy'), ('company_areas', 'Tikety firmy v konkrétních oblastech')], default='own', max_length=20, verbose_name='rozsah viditelnosti tiketů'),
        ),
    ]
