# Generated by Django 5.1.15 on 2026-06-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_requester_areas_user_requester_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_new_ticket',
            field=models.BooleanField(default=False, help_text='Řešitel dostane e-mail při vytvoření nového tiketu ve svých oblastech.', verbose_name='notifikace nového tiketu'),
        ),
    ]
