# Generated by Django 5.1.15 on 2026-04-14 17:48

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('problem', 'Hlášení problému'), ('development', 'Požadavek na vývoj'), ('improvement', 'Námět na zlepšení')], max_length=20, verbose_name='typ')),
                ('title', models.CharField(max_length=200, verbose_name='název')),
                ('description', models.TextField(verbose_name='popis')),
                ('area', models.CharField(choices=[('it', 'IT'), ('helios', 'Helios'), ('unknown', 'Neznámá')], default='unknown', max_length=20, verbose_name='oblast')),
                ('priority', models.CharField(choices=[('high', 'Vysoká'), ('medium', 'Střední'), ('low', 'Nízká')], default='medium', max_length=10, verbose_name='priorita')),
                ('status', django_fsm.FSMField(default='new', max_length=50, protected=True, verbose_name='stav')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='způsob vyřešení')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='důvod zamítnutí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='vyřešeno dne')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.company', verbose_name='firma')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='žadatel')),
                ('resolver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='řešitel')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tickets', to=settings.AUTH_USER_MODEL, verbose_name='obchodník')),
            ],
            options={
                'verbose_name': 'tiket',
                'verbose_name_plural': 'tikety',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='tiket')),
            ],
            options={
                'verbose_name': 'komentář',
                'verbose_name_plural': 'komentáře',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='hodiny')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tickets.ticket', verbose_name='tiket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_logs', to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
            ],
            options={
                'verbose_name': 'časový záznam',
                'verbose_name_plural': 'časové záznamy',
                'ordering': ['created_at'],
            },
        ),
    ]
