# Generated by Django 5.1.15 on 2026-04-15 21:25

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'Nový'), ('offer_prep', 'Příprava nabídky'), ('in_progress', 'Řeší se'), ('resolved', 'Vyřešeno'), ('rejected', 'Zamítnuto')], default='new', max_length=50, protected=True, verbose_name='stav'),
        ),
    ]
