# Generated by Django 5.1.15 on 2026-04-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_area_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='is_unknown',
            field=models.BooleanField(default=False, help_text='Tikety s touto oblastí nejsou omezeny oblastí správce.', verbose_name='neznámá oblast'),
        ),
    ]
