# Generated by Django 5.1.15 on 2026-04-22 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticketchange_values_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='název')),
                ('areas', models.ManyToManyField(blank=True, help_text='Prázdný výběr = kategorie platí pro všechny oblasti.', related_name='work_categories', to='tickets.area', verbose_name='oblasti')),
            ],
            options={
                'verbose_name': 'kategorie práce',
                'verbose_name_plural': 'kategorie práce',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.workcategory', verbose_name='kategorie práce'),
        ),
    ]
