# Generated by Django 5.1.15 on 2026-04-28 10:48

import django.core.validators
import uuid
from django.db import migrations, models


def populate_rating_tokens(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        ticket.rating_token = uuid.uuid4()
        ticket.save(update_fields=['rating_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_workcategory_ticket_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='hodnocení'),
        ),
        # Krok 1: přidat pole bez unique constraint, nullable
        migrations.AddField(
            model_name='ticket',
            name='rating_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='token hodnocení'),
        ),
        # Krok 2: naplnit unikátními UUID pro všechny existující řádky
        migrations.RunPython(populate_rating_tokens, migrations.RunPython.noop),
        # Krok 3: přidat unique constraint
        migrations.AlterField(
            model_name='ticket',
            name='rating_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token hodnocení'),
        ),
    ]
