# Generated by Django 5.1.15 on 2026-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_rating_ticket_rating_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating_comment',
            field=models.TextField(blank=True, verbose_name='komentář k hodnocení'),
        ),
    ]
