# Generated by Django 5.1.15 on 2026-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating_comment_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='token komentáře k hodnocení'),
        ),
    ]
