# Generated by Django 5.1.15 on 2026-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_rating_comment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_person_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail kontaktní osoby'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_person_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='jméno kontaktní osoby'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('problem', 'Podpora'), ('development', 'Požadavek'), ('improvement', 'Nápad')], max_length=20, verbose_name='typ'),
        ),
    ]
