# Generated by Django 5.1.15 on 2026-06-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='jméno')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_watchers', to='tickets.ticket', verbose_name='tiket')),
            ],
            options={
                'verbose_name': 'sledující',
                'verbose_name_plural': 'sledující',
                'ordering': ['name', 'email'],
                'unique_together': {('ticket', 'email')},
            },
        ),
    ]
