# Generated by Django 5.1.15 on 2026-06-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketwatcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='název')),
                ('params', models.JSONField(default=dict, verbose_name='parametry')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
            ],
            options={
                'verbose_name': 'uložený filtr',
                'verbose_name_plural': 'uložené filtry',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
